version: 0.2

env:
  variables:
    S3_BUCKET: "your-s3-bucket-name"  # Replace with your S3 bucket name
    STACK_NAME: "your-stack-name"     # Replace with your stack name

phases:
  install:
    runtime-versions:
      python: 3.10
      docker: 19
    commands:
      - pip install aws-sam-cli

  pre_build:
    commands:
      - echo "Logging in to Amazon ECR..."
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin <account-id>.dkr.ecr.<region>.amazonaws.com  # Replace with your account ID and region
      - echo "Building the SAM application..."
      - sam build

  build:
    commands:
      - echo "Packaging the SAM application..."
      - sam package --output-template-file packaged.yaml --s3-bucket $S3_BUCKET

  post_build:
    commands:
      - echo "Deploying the SAM application..."
      - sam deploy --template-file packaged.yaml --stack-name $STACK_NAME --capabilities CAPABILITY_IAM

artifacts:
  files:
    - packaged.yaml
  discard-paths: yes